import { ReactNode } from 'react';

import { Inter } from 'next/font/google';

import { Providers } from '@/components/common';
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <Providers>
        <body className="flex min-h-screen flex-col bg-gray-50">{children}</body>
      </Providers>
    </html>
  );
}
